server:
  port: 8000
spring:
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter # # ?? ???? class ??? ?? ? ? ??.
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true      
#      routes:
#        - id: first-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/first-service/**
#          filters:
#            - CustomFilter # ?? ???? class ??? ?? ? ? ??. 
#        - id: second-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true  # default: true